### ISSUE TITLE
How to deal with actions between admins

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#101]
Let us assume there are two admins: Trevor and Michael. Now, Michael has admin level 5 while Trevor is an admin of level 3. Trevor is always using `/freeze` on Michael to win the races. Even this is just a joke we maybe should add a check to prevent that admins with lower level can punish admins with higher level.

Any comments on that?

**Example:**

Possible way to check that would be the following.

**PPC_DefTexts.inc**

```pawn
#define TXT_AdminHasHigherLevel "The admin level of that admin is higher than yours."
```

**PPC_PlayerCommands.inc**

```pawn
if (APlayerData[playerid][PlayerLevel] < APlayerData[Player][PlayerLevel])
	return SendClientMessage(playerid, COLOR_RED, TXT_AdminHasHigherLevel)
```

**Comment by Yousha** [comment]
```
if (playerAdminRank > targetPlayerAdminRank)
{
   // Let him/her do actions on target player
```

This?

**Comment by CodeAlDente** [comment]
I have added an example to the initial issue description.

But the question is if we should add this as it is not really necessary but it could be useful in some situations as it prevents abuse of administration rights.

**Comment by CodeAlDente** [comment]
Maybe it would be better to exclude admins generally from punishment? I guess that server owners only give admin level if they trust the player. If an admin is abusing his power the owner can just remove his admin level.

If we keep allowing actions between admins such `/jail` we need extra checks at a lot of commands where admins can teleport as they will be sent back to jail if they teleport to an other place.

**Example:**

Possible way to check that would be the following.

**PPC_DefTexts.inc**

```pawn
#define TXT_PlayerIsAdmin "That player is an admin and you can not use that command on him."
```

**PPC_PlayerCommands.inc**

```pawn
if (APlayerData[Player][PlayerLevel] != 0)
	return SendClientMessage(playerid, COLOR_RED, TXT_PlayerIsAdmin)
```

---

To my mind, excluding admins from actions between each other is the best solution and we do not have to care about extra checks.

What do you guys think?

**Comment by Yousha** [comment]
Yea, this is what I did in many servers (and other developers)... staff shouldn't get punished by System. Specially in-front of online players 
Only a message is respective and enough
