### ISSUE TITLE
Check for PLAYER_STATE_WASTED on admin commands

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#102]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A check is needed to determine if a player has been spawned already before an admin can perform e.g. `/freeze` on him.

**Describe alternatives you've considered**
None.

**Additional context**
Possible way to check that would be the following.

**PPC_DefTexts.inc**

```pawn
#define TXT_PlayerNotSpawned "That player has not been spawned yet (dead or in class selection)."
```

**PPC_PlayerCommands.inc**

```pawn
if (GetPlayerState(playerid) == PLAYER_STATE_WASTED)
	return SendClientMessage(playerid, COLOR_RED, TXT_PlayerNotSpawned);
```

**Comment by CodeAlDente** [comment]
Exclude the following commands from that.

- [ ] `/kick`
- [ ] `/mute`
- [ ] `/unmute`
- [ ] `/warn`
- [ ] `/ban`

**Comment by Yousha** [comment]
Instead of making a long **blacklist**, let's make a short **whitelist**:

```
/**
   <summary>
      Checks if target player is spawned.
   </summary>

   <param name="playerid">
      Player game Id.
   </param>

   <returns>
      True/False
   </returns>
*/
bool:IsPlayerSpawned(const playerid)
{
   switch (GetPlayerState(playerid))
   {
      case PLAYER_STATE_ONFOOT, PLAYER_STATE_DRIVER, PLAYER_STATE_PASSENGER, PLAYER_STATE_SPAWNED:
      {
         return true;
      }
   }

   return false;
}
```

?
