### ISSUE TITLE
Check for PLAYER_STATE_SPECTATING on admin commands

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#103]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When an admin uses e.g. `/spec` on another admin there should be a warning given that this admin is currently spectating someone else.

**Describe alternatives you've considered**
None.

**Additional context**
Possible way to check that would be the following.

**PPC_DefTexts.inc**

```pawn
#define TXT_PlayerSpectating "You can not use that command because that player is currently spectating someone."
```

**PPC_PlayerCommands.inc**

```pawn
if (GetPlayerState(Player) == PLAYER_STATE_SPECTATING)
	return SendClientMessage(playerid, COLOR_RED, TXT_PlayerSpectating);
```

**Comment by Yousha** [comment]
Actually it is'nt `playerid`, it must be **TARGETplayerid** or something like that...

**Comment by CodeAlDente** [comment]
Obsolete now as of #101
