### ISSUE TITLE
Missing NPC check for player based commands

### ISSUE THREAD

**Issue by Yousha** [PPC-Trucking/V1#104]
**Describe the bug**
Players/Staff can perform action(command) on NPCs

**To Reproduce**
1. ... Add some NPC in-game
2. ... Use /kick /warn /report etc... on those NPCs
3. ...

**Expected behavior**
Players/Staff must NOT be allowed to perform cmd actions on NPCs. There must be a message or `return 0` 

**Screenshots**

**Additional context**
Using this function in ALL commands would help:

```
bool:IsPlayerInGame(const playerid)
{
   if (!IsPlayerConnected(playerid) || (playerid == INVALID_PLAYER_ID) || IsPlayerNPC(playerid))
   {
      return false;
   }

   return true;
}
```

**Comment by CodeAlDente** [comment]
By using `APlayerData[Player][LoggedIn]` which checks for connected and logged-in players we can safely make only use of `IsPlayerNPC` to determine an NPC.

~Not sure if it also includes actors or if an extra check is needed against `IsValidActor`, see https://wiki.sa-mp.com/wiki/Category:Actor.~ No need for.

**Comment by CodeAlDente** [comment]
As suggested I would prefer to let the player / admin know, that his action can not be performed on an NPC.

Although we should allow commands like `/givecash` later as we can use that to give some little jokes in a way like an NPC is saying thanks for the cash or even giving out a free trucking license. We can also use that given money to help players out who are in debt. Just some random ideas.
