### ISSUE TITLE
/gohome and /getvehicle don't work (NoHouseInSlot)

### ISSUE THREAD

**Issue by AlphaMajora** [PPC-Trucking/V1#112]
**Describe the bug**

When all the players try to do /gohome or getvehicle, they get this msg error : "You don't have a house in this house-slot"
But they own some houses. I try with no modification of the gamemode/includes, but the problem is present

**To Reproduce**

1. /gohome or /getvehicle

**Expected behavior**

It should work but, i don't know why, but it doesn't work. But /porthouse ID still work. So I think the problem is with the HouseID of players.

**Screenshots**

https://cdn.discordapp.com/attachments/464031240283226117/723913672245772319/unknown.png

https://cdn.discordapp.com/attachments/464031240283226117/723936943942926356/unknown.png

https://cdn.discordapp.com/attachments/464031240283226117/723937089917550723/unknown.png

**Additional context**

**Comment by CiprianN23** [comment]
Issues were introduced in the commit https://github.com/PPC-Trucking/V1/commit/d74b9c602eb7564577b22bd7635401684e7e05c7 
To resolve the issues revert changes made to the PPC_Dialog.inc file

**Comment by AlphaMajora** [comment]
Huge thanks to you ! It works !

**Comment by CodeAlDente** [comment]
Thank you both for pointing it out. That issue has been fixed.
