### ISSUE TITLE
Job text of weaponized class (Police) don't appear

### ISSUE THREAD

**Issue by AlphaMajora** [PPC-Trucking/V1#118]
**Describe the bug**
When players join a class with weapons, the job text below the screen don't appear.
I think i found the problem and the way to solve it, but it's not "clean code"

**To Reproduce**
1. Join police class (or other weaponized class if we add it with the same method as police class)

**Expected behavior**
The text must appear for weaponized class

**Screenshots**
I try change the function to apply weapon to player with a "while", but work the same as "for" function. The only way I found to make the text work, it's to add the line to apply weapons one by one.

(This is in the **PPC_Trucking.pwn** file)

![image](https://user-images.githubusercontent.com/64423271/85920134-7dd2be80-b871-11ea-8376-563d38b62595.png)

Entire code of police class case

![image](https://user-images.githubusercontent.com/64423271/85920294-dce50300-b872-11ea-8a84-6b1b8807c8d1.png)

**Additional context**

PS : Sorry for my bad english

**Comment by CodeAlDente** [comment]
Indeed there was a mistake in that loop as it did not take the certain number of elements in that array (`APoliceWeapons`). It must have caused an internal error. I have changed it so we are safe in the future if we add or remove weapons for the police class.

Thanks a lot for your work on this!
