### ISSUE TITLE
Unmute a player when he leaves the server

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#32]
Imagine you have muted a player and he leaves the server. If **(!)** he joins the server again, he would be still muted without the chance to ask for an unmute. Even all admins could be offline so there is no chance at all for him to participate in the game as he can not communicate with other players.

( Everyone deserves a second chance. :wink:  )

**Comment by CiprianN23** [comment]
Another way will be to add time to the mute command like /mute id 10(sec) reason, by using timestamp to avoid any unuseful timers but the bool that keep track of the player being mute will disapear, checks will be made by comparing the curent timestamp with the one saved in the player account. Just an idea

**Comment by CodeAlDente** [comment]
Yes, this is also possible. It would also unmute the player in case an admin forgot to unmute him. Maybe we should add both. A timestamp until the player is muted and a reset of this timer when the player leaves the server. What do you think?

We can set the timestamp in `APlayerData[playerid][Muted]`. It is currently used with a boolean value to determine if the player is muted or not.

**Comment by CiprianN23** [comment]
That will work actually, but i overthinking about a possible abuse from the player. 
Eg: Admin x mute player y for 60 secs, player y leaves server after 5-10 secs and when player y enter back he will not be muted

**Comment by CodeAlDente** [comment]
Correct. But that is what I am calling a second chance. If the player continues to spam or insult in chat, the admin can take other actions like warning him which results in a server kick after 3 (by default) times. He can also mute him again.

**Comment by CiprianN23** [comment]
Fair point. Should work

**Comment by CodeAlDente** [comment]
> /mute id 10(sec) reason

I will change that to minutes as it does not make any sense to mute for seconds only. Minimum will be 1 minute and maximum 60 minutes (one hour).
