### ISSUE TITLE
Fix command messages

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#33]
**Players**
- [x] `/bonus` (if player is not trucker)
- [ ] `/buybus` (check range to a business)
- [ ] `/detach` (in vehicle that supports trailer? any trailer connected?)
- [ ] `/eject` (player online?)
- [x] `/engine` (tell player whetver engine has been turned on or off)
- [x] `/enter` (any house or busines nearby to enter?)
- [ ] `/getcar` (check for any vehicles before displaying dialog)
- [ ] `/gobus` (any business owned by player?)
- [ ] `/gohome` (any house owned by player?)
- [ ] `/report` (player online?)
- [ ] `/gobase` (if only one spawn-location, e.g. assistance)
- [x] `/stopwork` (work started?)

**Admins**
- [x] `/ban` (player exists/found?)
- [x] `/car`, `/bike`, `/plane`, `/boat`, `/trailer` (on foot?)
- [ ] `/delcamera` (is it nearby?)
- [x] `/delobject` (object exists?)
- [ ] `/fixplayer` (player online?)
- [ ] `/givelicense` (player online?)
- [ ] `/healall` (tell player an admin healed him)
- [ ] `/ipban` (player found?)
- [x] `/jail` (already jailed?)
- [x] `/mute` (already muted?)
- [x] `/nos` (added? in vehicle, warn on foot)
- [x] `/portvehicle` (vehicle exists?)
- [ ] `/rangeban` (player found?)
- [x] `/rep` (are there any?)
- [ ] `/repairall` (tell player an admin repaired his vehicle)
- [ ] `/resetplayer` (player online? any changes?)
- [x] `/setlevel` (level in range?)
- [x] `/setskin` (skin-id in range?)
- ~`/unban` (is player banned?)~ Not necessary as value will just be overwritten.
- [x] `/unmute` (even muted?)
- [x] `/wanted` (confirm wanted level for admin, inform player about wanted level)
- [x] `/warn` (inform player he got kicked because of x warnings, then kick him)

**Comment by Yousha** [comment]
What do you mean by command message for "/eject (player online?)"

**Comment by CodeAlDente** [comment]
The intention was to check only if the player is connected to the server but there was a mistake on my side as we can check both: online status and login status in one way. Thanks for pointing this out!

We still need to return an error message for this though.

https://github.com/PPC-Trucking/V1/blob/9d4d28f7a15185c3fb0c83bf2b0ffa8b29adbce5/pawno/include/PPC_PlayerCommands.inc#L3978
