### ISSUE TITLE
Restrict access to commands if player has not been spawned

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#60]
Do **only allow** a player who has **not been spawned** yet to send messages (public / private via `/pm` and `/asay`) and to use the `/me` command. As all players (new / registered) have to login first, it is safe to allow to chat. **No one can pretend to be someone else (and write something bad in his name).** :+1:

- [x] ~~Create new variable that holds (boolean) if the player has been spawned yet or not. This variable is default set to `false` and if the player spawns the callback `OnPlayerSpawn` will set it to `true` while `OnPlayerDeath` sets it to `false` again.~~ We use `PLAYER_STATE_WASTED`
- [x] Do not allow other players to send private messages to a player who has not logged in.

**Comment by CiprianN23** [comment]
It can been done via player states. No need for extra variabiles. Using PLAYER_STATE_SPAWNED to check if the player its or not spawned. Just an idea

**Comment by CodeAlDente** [comment]
Very good point. [`PLAYER_STATE_WASTED`](http://wiki.sa-mp.com/wiki/Player_states) would perfectly fit in here as it deals with both: dead and on class-selection.

**Comment by CodeAlDente** [comment]
- [ ] Do not only use `PLAYER_STATE_WASTED` but also `PLAYER_STATE_SPECTATING` (for admins). Do also check if players have been spawned when using commands like `/freeze` on them.

see #102 #103

**Comment by CodeAlDente** [comment]
- [x] Check against `PLAYER_STATE_WASTED ` on `OnPlayerCommandReceived` to determine whether the player has been spawned.

**Comment by CodeAlDente** [comment]
Do only allow the following actions to perform while in class selection:

- [x] send public text messages
- [x] send / receive private messages
- [x] `/me`
