### ISSUE TITLE
Increase readablity of amount (money) by using comma as separator

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#61]
Right now you are seeing messages like `You gave $21523156 to ...`. We must format the money ending up in a message like `You gave $21,523,156 to ...` for a better overview.

**Comment by CiprianN23** [comment]
Using formatex will be kinda easier to do this via this function: http://forum.sa-mp.com/showpost.php?p=1651741&postcount=19

**Comment by CodeAlDente** [comment]
I was also thinking about to use an extra include but then I found a really nice function which can also be used to format the distances driven.

```pawn
stock FormatNumber(iNum, const szChar[] = ",")
{
	new szStr[16], bool:negative = false;

	if (0 > iNum)
		negative = true;

	if (negative)
		iNum = -iNum;

	format(szStr, sizeof(szStr), "%i", iNum);

	for(new iLen = strlen(szStr) - 3; iLen > 0; iLen -= 3)
		strins(szStr, szChar, iLen);

	if (negative)
		strins(szStr, "-", 0, sizeof(szStr));

	return szStr;
}
```

source: http://forum.sa-mp.com/showpost.php?p=843781

**Comment by Yousha** [comment]
> 
> 
> I was also thinking about to use an extra include but then I found a really nice function which can also be used to format the distances driven.
> 
> ```pawn
> stock FormatNumber(iNum, const szChar[] = ",")
> {
> 	new
> 		szStr[16]
> 	;
> 	format(szStr, sizeof(szStr), "%d", iNum);
> 	
> 	for(new iLen = strlen(szStr) - 3; iLen > 0; iLen -= 3)
> 	{
> 		strins(szStr, szChar, iLen);
> 	}
> 	return szStr;
> }
> ```
> 
> source: http://forum.sa-mp.com/showpost.php?p=843781

Your function doesn't work well with **Negative numbers**...

`FormatNumber(-123456);`

Result: -,123,456

**Comment by CodeAlDente** [comment]
In that case the suggested modifier (https://github.com/PPC-Trucking/V1/issues/61#issuecomment-359241458) would be a much better option.

**Comment by Yousha** [comment]
Or this one:
```
FormatNumber(number)
{
   new numberString[32];
   new lenght, bool:negativeFlag;

   if (number < 0)
   {
      negativeFlag = true;
      number = -number;
   }

   valstr(numberString, number, false);

   for (lenght = strlen(numberString); lenght > 3; lenght -= 3)
   {
      strins(numberString, ",", lenght - 3, sizeof(numberString));
   }

   if (negativeFlag)
   {
      strins(numberString, "-", 0, sizeof(numberString));
   }

   return numberString;
}
```

Already tested and used in production env.

**Comment by CodeAlDente** [comment]
I have updated the function. It works now for negative values as well.
