### ISSUE TITLE
Add support for translations - PlayerCommands

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#7]
Change all the static texts into variables so we can use them later for translations.

**Comment by CodeAlDente** [comment]
This requires a platform where we can submit translation for the different texts in the Gamemode. Thinking of www.otrance.org but it's quite outdated...

**Comment by CodeAlDente** [comment]
We have just started with the commands.

**Comment by Yousha** [comment]
Using variable instead of static text (or a-least `define`) consumes **memory**... 


IMO, it's better to use `define` and put them in a LOCALES folder.

Ex:
includes/locales/english.inc
includes/locales/spanish.inc
includes/locales/persian.inc
...

So developer/owner can include any of them

**Comment by CodeAlDente** [comment]
That is exactly what we do right here: https://github.com/PPC-Trucking/V1/blob/master/pawno/include/PPC_DefTexts.inc

When the translation is completed we reorganize the structure as well.

**Comment by Yousha** [comment]
Do you mind to change names to something like this:

```
LOCALE_ACTION_CANCEL
LOCALE_ACTION_CLOSE

LOCALE_TITLE_OPTIONS
LOCALE_TITLE_SETTINGS

LOCALE_MESSAGE_CANTBEEMPTY
LOCALE_MESSAGE_NOTLOGGEDIN
...
```

or

```
TEXT_ACTION_CANCEL
TEXT_ACTION_CLOSE

TEXT_TITLE_OPTIONS
TEXT_TITLE_SETTINGS

TEXT_MESSAGE_CANTBEEMPTY
TEXT_MESSAGE_NOTLOGGEDIN
...

```

**Comment by CodeAlDente** [comment]
Sure. I wanted to change the names of the translation identifiers anyway to uppercase. Doing so we can create new folders and own structure for the language files as well.

I wanted to setup an online translation center for this, too. But that is something for later.
