### ISSUE TITLE
ROOT/pawno/include/...

### ISSUE THREAD

**Issue by Yousha** [PPC-Trucking/V1#83]
This directory `pawno/include/` is used to include **PAWN libs**, not game-mode stuff such functions, vars etc...
So it's better to move them to its own directory` ROOT/include/`

Also it makes problems with **sampctl**, which is a Package Management and Build Tool for SAMP/PAWN

**Comment by CodeAlDente** [comment]
Good point! Will be considered in next release.

- [ ] Change structure of folders
- [ ] Update README
- [ ] Look through wiki
