### ISSUE TITLE
Check for valid ranges in certain commands

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#91]
Check for a valid range of values in commands, e.g. `/setwanted` where we can set a wanted level. A valid range would be from 0 (no wanted level) up to 6.

- [x] `/givecash`
- [x] `/paint`
- [ ] `/freeze`
- [x] `/jail`
- [x] `/mute`
- [x] `/announce`
- [x] `/setwanted`
- [x] `/ban`
- [x] `/setskin`
- [ ] `/createcamera`
- [ ] `/createhouse`
- [x] `/resetplayer`
- [x] `/setlevel`

\* Some of these commands may have a check for a valid range already.

**Comment by Yousha** [comment]
What if players in that range were in different **Interior** or **Virtual World** ?

**Comment by CodeAlDente** [comment]
What do you mean? Any example?

**Comment by Yousha** [comment]
- For example you and your friends are inside a building(house, shop etc) with Interior 1 and VirtualWorld 1, another player is there but in VirtualWorld 2 (so he/she is invisible from you and your friends)

- Then you perform a `/freeze 25` which freezes any player in range 25... or even `/jail 60 25`!

- Now ALL innocent players in range 25 are frozen or jailed! even those in other VirtualWorlds

**Comment by CodeAlDente** [comment]
Oh I see. I guess I did not properly explain the goals of this issue. My intention was to check the ranges of the given values in the commands.

When an admin is using `/freeze` it must be checked that he provides a minimum of one second. So it is meant to check the range of the given parameters, e.g. seconds, not the range in which the players stay next to each other.
