### ISSUE TITLE
izcmd instad of zcmd

### ISSUE THREAD

**Issue by Yousha** [PPC-Trucking/V1#95]
**Is your feature request related to a problem? Please describe.**
**izcmd**(improved version) include has better performance than **zcmd**(old version)

**Describe the solution you'd like**
Replace **izcmd** include with **zcmd**.

**Describe alternatives you've considered**

**Additional context**
https://github.com/YashasSamaga/I-ZCMD/blob/master/izcmd.inc

**Comment by CodeAlDente** [comment]
Looks promising. We should consider to replace `zcmd` with that in a later version.

- [ ] Update README
