### ISSUE TITLE
Crash when using /announce with style id 6 and tilds

### ISSUE THREAD

**Issue by CodeAlDente** [PPC-Trucking/V1#99]
**Describe the bug**
I was trying out screen messages for players in case they get kicked. Just like we have them for `/mute`. When I am using `/announce 6 5 ~w~you have been ~n~ ~r~kicked` the game crashes.

**To Reproduce**
1. Join server
2. Login
3. Use `/announce 6 5 ~w~you have been ~n~ ~r~kicked` (admin level required)

**Expected behavior**
The command should show the given message just like in other styles.

**Screenshots**

**Additional context**
It seems like only style id 6 is affected. When I am using `/announce 6 5 ~w~you have been` it works without problems. Even when I am using  `/announce 6 5 ~w~hello world ~n~ ~r~goodbye` it works without crashing.

Would it be a solution to exclude style id 6 from `/announce` and to block tilds at all there?

**Comment by CiprianN23** [comment]
https://wiki.sa-mp.com/wiki/GameTextStyle

As stated here, some of the style dont work with to many special characters or colors. I would say style 4 fits better that kind of message.

Also style 2  needs remove as will be staying there until respawn

**Comment by CodeAlDente** [comment]
Alright. I am just confused that other messages work...

In that case I would suggest to change the current feedback screen messages with style id 6 to 4, see e.g. `/mute`.

Along with that we should now also exclude style id 6 from `/announce`. Style id 2 is already excluded.

- [x] Update `/help` and wiki

**Comment by CodeAlDente** [comment]
Fixed in 626a7f4bc313b7f6eefcc3be4e16f02de1654a36
